/*
 * generated by Xtext 2.33.0
 */
package lip6.move.ahg.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import lip6.move.ahg.AHGRuntimeModule;
import lip6.move.ahg.AHGStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AHGIdeSetup extends AHGStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AHGRuntimeModule(), new AHGIdeModule()));
	}
	
}
