/*
 * generated by Xtext 2.33.0
 */
package lip6.move.ahg.ui.tests;

import com.google.inject.Injector;
import lip6.move.ahg.ui.internal.AhgActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AHGUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AhgActivator.getInstance().getInjector("lip6.move.ahg.AHG");
	}

}
