/*
 * generated by Xtext 2.33.0
 */
package lip6.move.ahg;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AHGRuntimeModule extends AbstractAHGRuntimeModule {
}
