/*
 * generated by Xtext 2.33.0
 */
package lip6.move.ahg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AHGUiModule extends AbstractAHGUiModule {

	public AHGUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
